export const BVC_RESPONSE_CODES: Record<string, string> = {
  // --- VALIDACIONES DE CAMPOS Y FORMULARIO ---
  "NAME-EMPTY": "Sin datos en campo Nombre Titular",
  "CIRIF-EMPTY": "Sin datos en el campo Cédula o Rif",
  "CIRIF-NAN": "Cédula o RIF inválido (no numérico)",
  "CIRIF-INVALID": "Cédula o RIF inválido. Por favor verificar",
  "ACC-EMPTY": "Sin datos en el campo Número de Cuenta",
  "ACC-NAN": "Cuenta inválida. Verifique (No Numérica)",
  "ACC-INVALID": "Cuenta inválida o no coincide con la identificación",
  "PAYMENT-METHOD-EMPTY": "Modalidad no definida",
  "CONCEPT-INCOMPLETE": "El campo concepto debe ser mayor a 3 caracteres",
  "EMAIL-EMPTY": "Correo vacío. Verificar",
  "EMAIL-INVALID": "Correo inválido. Verificar",
  "PHONE-INVALID": "Teléfono inválido. Formato esperado: 04XXXXXXXXX",
  "ADDRESS-INCOMPLETE": "El campo dirección debe ser mayor a 4 caracteres",
  "AMOUNT-EMPTY": "Sin datos en el campo Monto",
  "AMOUNT-NAN": "El monto de factura no es numérico",
  "AMOUNT-INVALID": "El monto de la factura no es válido",
  "IVA-NAN": "El monto de IVA no es numérico",
  "ORDER-INVALID": "Sin datos en el número de Factura",
  "PAYMENT-ID-EMPTY": "Datos del ID del Pago vacíos",
  "PAYMENT-NUL": "Pago no existente",
  "PAYMENT-INVALID": "Pago ya procesado anteriormente o invalido",

  // --- ERRORES TÉCNICOS, CIFRADO Y SISTEMA ---
  "ENCRYPT-ENCODEERROR": "Error en el encriptado (llaves o vector)",
  "GENERIC-BVC-ERROR": "Error general interno del banco (BD/Mainframe)",
  "ENCRYPT-ALGORITHM-ERROR":
    "Error en el algoritmo de encriptación (AES128 requerido)",
  "SYSTEM-ERROR": "Error general del sistema",
  "ENCODING-ERROR": "Error de encoding (No se logró con UTF-8)",
  "DECRYPT-ERROR": "Error al desencriptar. Verificar llave/vector",
  "BD-ERROR": "Error de Base de Datos. Intente generar el token nuevamente",
  "BD-ERROR-PAYMENT":
    "Error de BD. El cobro pudo haberse realizado. Contactar soporte",
  "TX-ERROR": "Error al buscar el pago (HTTP 400)",
  "PAYMENT-NOT-FOUND":
    "Pago no encontrado con los datos suministrados (HTTP 404)",

  // --- RESPUESTAS DE PUNTO DE VENTA (ISO 8583) ---
  "00": "APROBADA",
  "01": "LLAMAR AL EMISOR",
  "02": "LLAMAR AL EMISOR, CONDICIÓN ESPECIAL",
  "03": "CÓDIGO COMERCIO INVÁLIDO",
  "04": "PICAR TARJETA",
  "05": "NO HONRRADA",
  "06": "ERROR",
  "07": "PICAR TARJETA, CONDICIÓN ESPECIAL",
  "11": "CÓDIGO VIP DE APROBACIÓN",
  "12": "TRANSACCIÓN INVÁLIDA",
  "13": "MONTO INVÁLIDO",
  "14": "NÚMERO DE TARJETA INVÁLIDA",
  "15": "NO APROBADA POR EMISOR",
  "19": "OPERACIÓN REENTRANTE (NO APROBADA)",
  "21": "NO SE TOMÓ NINGUNA ACCIÓN (NO APROBADA)",
  "25": "ARCHIVO NO DISPONIBLE",
  "28": "ARCHIVO NO DISPONIBLE",
  "30": "FORMATO ERRADO",
  "41": "TARJETA PERDIDA",
  "43": "TARJETA ROBADA",
  "51": "SALDO INSUFICIENTE",
  "52": "NO EXISTE CUENTA",
  "53": "NO EXISTE CUENTA",
  "54": "TARJETA EXPIRADA",
  "55": "CLAVE INCORRECTA",
  "57": "TRANSACCIÓN NO PERMITIDA",
  "61": "EXCEDE LÍMITE DIARIO DE MONTO",
  "62": "TARJETA RESTRINGIDA",
  "63": "VIOLACIÓN DE SEGURIDAD",
  "65": "EXCEDE EN CANTIDAD DE OPERACIONES",
  "75": "EXCEDE INTENTOS DE CLAVE ERRADA",
  "76": "INVÁLIDO MENSAJE DE ENVÍO",
  "77": "INCONSISTENCIA DE INFORMACIÓN",
  "80": "FECHA INCORRECTA",
  "81": "CÉDULA O CVV INVÁLIDO",
  "82": "INCORRECT CVV",
  "83": "UNABLE TO REIFY PIN",
  "85": "DECLINADA LA SOLICITUD",
  "91": "CONEXIÓN INOPERATIVA ENTRE INSTITUCIONES",
  "93": "OPERACIÓN NO COMPLETADA",
  "96": "MAL FUNCIONAMIENTO DEL SISTEMA",
  N0: "NO APROBADA",
  N3: "NO TIENEN SERVICIO PARA RETIRAR",
  N4: "RETIRO DE DINERO EXCEDE LÍMITE",
  XA: "ENVIADO AL EMISOR",
  XD: "ENVIADO AL EMISOR",

  // --- ERRORES PAGO MÓVIL (P2P / C2P) ---
  E001: "Cliente no registrado",
  E002: "Teléfono no registrado",
  E003: "Registro no existe",
  E006: "Tipo de cuenta a debitar errado",
  E007: "No tiene asociado ese tipo de cuenta",
  E008: "Tipo de cuenta beneficiario errado",
  E009: "Beneficiario no tiene ese tipo de cuenta",
  E010: "Monto no válido",
  E012: "Teléfono no habilitado para pagar",
  E013: "Excede cantidad de pagos diarios",
  E014: "Excede monto total de pagos diarios",
  E015: "Excede monto máximo para un pago",
  E016: "Excede cantidad de pagos mensuales",
  E017: "Excede monto mensual de pagos",
  "017": "No se concreto la verificación del token.",
  E018: "Error en número de banco",
  E019: "Banco no autorizado para pagos",
  E020: "No tiene asociado ese tipo de cuenta",
  E021: "Teléfono receptor no registrado",
  E022: "Teléfono receptor no acepta pagos",
  E023: "Identificación del beneficiario no coincide",
  E024: "Cliente bloqueado",
  E028: "No existe o no coincide OTP",
  E029: "OTP Vencido",
  E030: "Banco no activo en Pago Móvil",
  E038: "Número de afiliado no registrado",
  E039: "Afiliado no concuerda con Rif",
  E040: "Anulación errada",
  E041: "No se puede anular",
  E042: "Categoría de comercio errada",
  E043: "Dirección del comercio errada",
  E044: "Código afiliado errado",
  E045: "Merchant no registrado",
  E053: "Pago no encontrado",
  E054: "Terminal no existe",
  E055: "Terminal no pertenece al Merchant",
  N002: "Cédula/Rif no numérica",
  N008: "Cuenta corriente no numérica",
  N040: "Data original no válida",
  N041: "Referencia inválida",
  N042: "Fecha no numérica",
  N043: "Banco inválido",
  N044: "Merchant no numérico",
  V001: "Nombre de programa en blanco",
  V002: "Nacionalidad Cédula/Rif no válida",
  V017: "Tipo de cuenta no válido",
  "0005": "Tiempo de respuesta excedido",
  "0012": "Transacción no válida",
  "0013": "Monto inválido",
  "0014": "Nro. del receptor errado/no afiliado",
  "0021": "Error en reverso/anulación",
  "0022": "Cédula/Rif receptor errada",
  "0030": "Error de formato",
  "0041": "Servicio no activo",
  "0043": "Servicio no activo",
  "0051": "Saldo insuficiente",
  "0055": "Clave temporal (OTP) inválida",
  "0056": "Celular no coincide",
  "0057": "Negada por el receptor",
  "0062": "Cuenta restringida",
  "0080": "Autorizador/Red no disponible",
  "0084": "Time-out",
  "0091": "Institución no disponible",
  "0092": "Banco receptor no afiliado",
  "0096": "Error en sistema",
  "0296": "Error en archivo de parámetros",
  "0996": "Error en longitud del mensaje",
  "0997": "Programa llamado directamente",
  "0998": "Programa de interfaz no válido",
  "0999": "No tiene acceso a esa interfaz",
  "3096": "Error código moneda",

  // --- ESTADOS CRÍTICOS DE CUENTA (PREFIJO 7F) ---
  "7F02": "Cuenta no acepta débitos",
  "7F03": "A nombre de menor",
  "7F06": "Bloqueo por fianza",
  "7F0H": "Congelada judicialmente",
  "7F0I": "Cliente difunto",
  "7F0J": "Consulte al gerente",
  "7F0K": "Cuenta inactiva",
  "7F0O": "Requiere dos firmas",
  "7F11": "Número de cuenta errado",
  "7F14": "Cuenta cerrada",
  "7F1B": "Requiere autorización",
  "7F2A": "Monto muy grande",
  "7F2J": "Interés no abonado",
  "7F4C": "Solo por taquilla",
  "7F5M": "Cuenta cerrada",

  // --- INTERFAZ CON SISTEMA SAFE (8000+) ---
  "8001": "Error en la interfaz con SAFE",
  "8002": "Área menor/mayor al permitido",
  "8003": "Opción enlace PGM no válida",
  "8004": "Código de canal no existe",
  "800P": "Error en la interfaz con SAFE",
  "8011": "No pudo aplicar la comisión",
  "8012": "No pudo aplicar el crédito",
  "801B": "No pudo reversar el débito",
  "801K": "No pudo reaplicar el débito",
  "801L": "No pudo reversar el crédito",
  "801M": "Transacción no autorizada",
  "801T": "SAFE no abierto",
  "80ZO": "Negada con error en cero",
  "800X": "Información de tarjeta no numérica",
  "8805": "Negada por SAFE",
  "8996": "Error en interfaz con SAFE",
  "9805": "Error en interfaz con SAFE",
  "9896": "Error en interfaz con SAFE",
  "9996": "Error en interfaz con SAFE",

  // --- ÉXITOS ---
  Pagado: "Pago realizado satisfactoriamente",
  ACCP: "Transacción Aceptada",
  G00: "Aprobado",

  UNKNOWN_CODE: "Código de error desconocido",
};

/**
 * Translates a BVC code to a human-readable message.
 */
export const translateBvcCode = (code: string): string => {
  // 1. Try to find it in the Internal API errors (EPI...)
  if (BVC_RESPONSE_CODES[code]) {
    return BVC_RESPONSE_CODES[code];
  }

  // 3. Fallback for unknown codes
  return `Error bancario no catalogado (${code})`;
};
