import CryptoJS from "crypto-js";

/**
 * Encrypts data for the 'dt' field.
 * Returns a Base64 string.
 */
export const bvcEncrypt = (data: object, key: string, iv: string): string => {
  const jsonString = JSON.stringify(data);

  // Parse key and IV to WordArrays
  const parsedKey = CryptoJS.enc.Utf8.parse(key);
  const parsedIv = CryptoJS.enc.Utf8.parse(iv);

  const encrypted = CryptoJS.AES.encrypt(jsonString, parsedKey, {
    iv: parsedIv,
    mode: CryptoJS.mode.CBC,
    padding: CryptoJS.pad.Pkcs7, // Equivalent to PKCS5 padding
  });

  return encrypted.toString(); // Default toString() in CryptoJS is Base64
};

/**
 * Decrypts the bank's response.
 * Parses the Base64 string back into the expected JSON type.
 */
export const bvcDecrypt = <T>(
  encryptedBase64: string,
  key: string,
  iv: string,
): T => {
  const parsedKey = CryptoJS.enc.Utf8.parse(key);
  const parsedIv = CryptoJS.enc.Utf8.parse(iv);

  const decrypted = CryptoJS.AES.decrypt(encryptedBase64, parsedKey, {
    iv: parsedIv,
    mode: CryptoJS.mode.CBC,
    padding: CryptoJS.pad.Pkcs7,
  });

  const decryptedText = decrypted.toString(CryptoJS.enc.Utf8);
  return JSON.parse(decryptedText) as T;
};

/**
 * Generates a deterministic SHA-256 hash to act as a permanent idempotency key.
 * @param creditorID - The recipient's ID (V12345678)
 * @param amount - The transaction amount (10.50)
 * @param mainAppReference - The unique ID generated by the client/mainApp
 */
export const createReference = (
  creditorID: string,
  amount: number | string,
  mainAppReference: string,
): string => {
  const formattedAmount =
    typeof amount === "number" ? amount.toFixed(2) : amount;

  const identityString = `${creditorID.trim().toUpperCase()}|${formattedAmount}|${mainAppReference.trim()}`;

  const hash = CryptoJS.MD5(identityString).toString(CryptoJS.enc.Hex);

  return hash.substring(0, 15).toUpperCase();
};
